name: vexana
description: Manage your network layer with dio. You will be able to use it very
  easily network operations.
author: Veli Bacik <vbacik.10@gmail.com>
version: 2.0.0-nullsafety.1
homepage: https://github.com/VB10/vexana

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0-beta4
  path_provider: ^2.0.1
  pedantic: ^1.11.0
  shared_preferences: ^2.0.3
  sembast: ^3.0.0+4
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  path_provider_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.0.0
