name: vexana
description: Manage your network layer with dio. You will be able to use it very
  easily network operations.
author: Veli Bacik <vbacik.10@gmail.com>
version: 1.3.1
homepage: https://github.com/VB10/vexana

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0-beta2
  path_provider: ^2.0.0
  pedantic: ^1.10.0
  shared_preferences: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  path_provider_platform_interface: ^2.0.0
  plugin_platform_interface: ^2.0.0
