name: vexana
description: Manage your network layer with dio. You will be able to use it very
  easily network operations.
version: 3.5.4
homepage: https://github.com/VB10/vexana

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  #Due to xcode 15 & ios 17 crash bug its fetched from github should be redirected to pubspec after fix
  connectivity_plus:
    git:
      url: https://github.com/fluttercommunity/plus_plugins.git
      path: packages/connectivity_plus/connectivity_plus
      ref: cf7d93fbfc76830acf2db755543cf4235a49df60

  # Core
  dio: ^5.3.1

  flutter:
    sdk: flutter

  # Log
  logger: ^2.0.0

  lottie: ^2.1.0

  # Database
  path_provider: ^2.0.1

  # Utility
  retry: ^3.1.0
  sembast: ^3.3.1+1
  sembast_web: ^2.0.1+1
  shared_preferences: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
  mockito: ^5.0.0
  path_provider_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.0.0+1

flutter:
  assets:
    - assets/lottie/
