name: Analyze the code when a new push and PR
run-name: Analyze action triggered by @${{ github.actor }}

# This action will only work when push and PR to "main" branch.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
  # "workflow_dispatch" for manual trigger
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze the Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: subosito/flutter-action@master
        with:
          channel: "stable"
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze lib example/lib
